/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout.index'
import { Route as LayoutHistoryImport } from './routes/_layout.history'
import { Route as AuthLayoutImport } from './routes/_auth/_layout'
import { Route as LayoutStaffUsersImport } from './routes/_layout.staff/users'
import { Route as LayoutStaffItemsImport } from './routes/_layout.staff/items'
import { Route as LayoutStaffLayoutImport } from './routes/_layout.staff/_layout'
import { Route as LayoutStaffLayoutIndexImport } from './routes/_layout.staff/_layout.index'
import { Route as AuthLayoutRegisterIndexImport } from './routes/_auth/_layout/register/index'
import { Route as AuthLayoutLoginIndexImport } from './routes/_auth/_layout/login/index'

// Create Virtual Routes

const LayoutStaffImport = createFileRoute('/_layout/staff')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutStaffRoute = LayoutStaffImport.update({
  path: '/staff',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHistoryRoute = LayoutHistoryImport.update({
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_auth/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutStaffUsersRoute = LayoutStaffUsersImport.update({
  path: '/users',
  getParentRoute: () => LayoutStaffRoute,
} as any)

const LayoutStaffItemsRoute = LayoutStaffItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutStaffRoute,
} as any)

const LayoutStaffLayoutRoute = LayoutStaffLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutStaffRoute,
} as any)

const LayoutStaffLayoutIndexRoute = LayoutStaffLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutStaffLayoutRoute,
} as any)

const AuthLayoutRegisterIndexRoute = AuthLayoutRegisterIndexImport.update({
  path: '/register/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutLoginIndexRoute = AuthLayoutLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/staff': {
      id: '/_layout/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof LayoutStaffImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/staff/_layout': {
      id: '/_layout/staff/_layout'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof LayoutStaffLayoutImport
      parentRoute: typeof LayoutStaffRoute
    }
    '/_layout/staff/items': {
      id: '/_layout/staff/items'
      path: '/items'
      fullPath: '/staff/items'
      preLoaderRoute: typeof LayoutStaffItemsImport
      parentRoute: typeof LayoutStaffImport
    }
    '/_layout/staff/users': {
      id: '/_layout/staff/users'
      path: '/users'
      fullPath: '/staff/users'
      preLoaderRoute: typeof LayoutStaffUsersImport
      parentRoute: typeof LayoutStaffImport
    }
    '/_auth/_layout/login/': {
      id: '/_auth/_layout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/register/': {
      id: '/_auth/_layout/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthLayoutRegisterIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_layout/staff/_layout/': {
      id: '/_layout/staff/_layout/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof LayoutStaffLayoutIndexImport
      parentRoute: typeof LayoutStaffLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutHistoryRoute,
    LayoutIndexRoute,
    LayoutStaffRoute: LayoutStaffRoute.addChildren({
      LayoutStaffLayoutRoute: LayoutStaffLayoutRoute.addChildren({
        LayoutStaffLayoutIndexRoute,
      }),
      LayoutStaffItemsRoute,
      LayoutStaffUsersRoute,
    }),
  }),
  AuthLayoutRoute: AuthLayoutRoute.addChildren({
    AuthLayoutLoginIndexRoute,
    AuthLayoutRegisterIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/_auth/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/history",
        "/_layout/",
        "/_layout/staff"
      ]
    },
    "/_auth/_layout": {
      "filePath": "_auth/_layout.tsx",
      "children": [
        "/_auth/_layout/login/",
        "/_auth/_layout/register/"
      ]
    },
    "/_layout/history": {
      "filePath": "_layout.history.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout.index.tsx",
      "parent": "/_layout"
    },
    "/_layout/staff": {
      "filePath": "_layout.staff",
      "parent": "/_layout",
      "children": [
        "/_layout/staff/_layout",
        "/_layout/staff/items",
        "/_layout/staff/users"
      ]
    },
    "/_layout/staff/_layout": {
      "filePath": "_layout.staff/_layout.tsx",
      "parent": "/_layout/staff",
      "children": [
        "/_layout/staff/_layout/"
      ]
    },
    "/_layout/staff/items": {
      "filePath": "_layout.staff/items.tsx",
      "parent": "/_layout/staff"
    },
    "/_layout/staff/users": {
      "filePath": "_layout.staff/users.tsx",
      "parent": "/_layout/staff"
    },
    "/_auth/_layout/login/": {
      "filePath": "_auth/_layout/login/index.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/register/": {
      "filePath": "_auth/_layout/register/index.tsx",
      "parent": "/_auth/_layout"
    },
    "/_layout/staff/_layout/": {
      "filePath": "_layout.staff/_layout.index.tsx",
      "parent": "/_layout/staff/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
